### ISSUE TITLE
Change course membership routes

### ISSUE THREAD

**Issue by martinvehmas** [ve-backend-internship-spring2022/EduManagementLab#39]
Change the route for POSTing a membership. Add an "s" att the end. You post a membership to the memberships collection.
Change the route for DELETEing a membership. Add an "s" and the userId for the user membership that is going to be deleted.

![image](https://user-images.githubusercontent.com/3663922/151796191-a1c067ec-3515-4a31-9ed3-6020ec1ca85a.png)

**Comment by natthaphongphengsa** [comment]
should i change the name on Method as well? 
![image](https://user-images.githubusercontent.com/72554303/151800695-bd4cb637-e24d-4e6a-8644-30f526ebde26.png)

**Comment by martinvehmas** [comment]
I think the name of the method is good. You update a membership.

But in the route you specify that you want to update one record in the collection memberships by adding a userId to the route.
