### ISSUE TITLE
Should membership methods return courseDtos?

### ISSUE THREAD

**Issue by EdGustafsson** [ve-backend-internship-spring2022/EduManagementLab#51]
![image](https://user-images.githubusercontent.com/74013934/152530974-49ede801-5ee2-4d9e-8c23-b5183ecf7231.png)

Currently when you add a membership and update enrollment date you get a CourseDto in response rather than a membershipDto, should this be changed?

**Comment by martinvehmas** [comment]
Yes I think its better to return a membershipDto.

And maybe the DeleteCourseMembership should not return an object? Only a ActionResult like DeleteCourse.

**Comment by EdGustafsson** [comment]
> And maybe the DeleteCourseMembership should not return an object? Only a ActionResult like DeleteCourse.

Yes i had the same idea, has to be changed in service layer. Currently the CourseService methods return course objects to the controllers.

**Comment by martinvehmas** [comment]
I looked at other API standards and some are returning the Group object when changing memberships.

For example the SCIM standard. http://www.simplecloud.info/

See Octas developer documentation for a more developer friendly description.
https://developer.okta.com/docs/reference/scim/scim-20/#update-a-specific-group-name
